services:
  super-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/auth-app
      - /auth-app/node_modules
    command: pnpm run dev
    env_file:
      - .env
    depends_on:
      - mongo-db
    networks:
      - super-net

  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - super-net

networks:
  super-net:
    driver: bridge

volumes:
  mongo-data:
